name: movie_night_tcc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

flutter_gen:
  outputs: lib/gen/

  integrations:
    flutter_svg: true
